### ISSUE TITLE
[error] constraintVal = 0 when evaluating constraints

### ISSUE THREAD

**Issue by kmindspark** [ipc-sim/IPC#19]
I get this error when trying to run IPC on a custom rope mesh.

```[error] constraintVal = 0 when evaluating constraints -70 21 10 480
       0  8.90364 0.155414
      0 8.83411  0.1542
       0  8.80866 0.153756
       0  8.99863 0.157072
```

A friend is able to run the same .txt file with the same mesh on a different computer. Do you have any suggestions on what the root cause may be? The tutorials run fine for me.

**Comment by liminchen** [comment]
I think this can be floating-point arithmetic issue. The error means that 0 distance primitive pairs on the input are detected. It could be that the compiler over-optimized floating-point arithmetic so that it is fast but not accurate?

**Comment by kmindspark** [comment]
Hmm...I've tried varying meshes but the issue seems to remain. Do you know if there is a way to turn off this "over-optimization" of floating point arithmetic?

**Comment by zfergus** [comment]
You can try to build in Debug mode to remove all optimizations. This should help rule this out.

**Comment by kmindspark** [comment]
I actually just ran the cmake and make commands once more and the error disappeared. Not sure why, but it works now :)
