### ISSUE TITLE
Ask for reference 

### ISSUE THREAD

**Issue by FantasyVR** [ipc-sim/IPC#2]
I've been looking for details about how to constructing the stiffness matrix, though I know the general steps according to the [siggraph course](http://www.femdefo.org/). 

I'm stuck here, how to compute the derivatives of the First Piola-Kirchhoff stress tensor with respect to deformation gradient?
https://github.com/ipc-sim/IPC/blob/c2206eaf76775978d5cab93b17f0b86bed04db76/src/Energy/Energy.cpp#L463
 it there any resource that I can follow so that I can finally understand this.

**Comment by liminchen** [comment]
Chapter 6 of https://www.seas.upenn.edu/~cffjiang/research/mpmcourse/mpmcourse.pdf has some derivation on it.
