### ISSUE TITLE
Docs for integration into existing project

### ISSUE THREAD

**Issue by xarthurx** [ipc-sim/IPC#25]
Hi, I just got to know this paper the found it is amazingly open-sourced!

By briefly reading the doc, it seems (correct me if I'm wrong) the current code is meant to be used as independent software.

Is it possible / Is there any doc for integrating it into an existing project in a library mode?
Say, I'd like to run the simulation in my own OpenGL environment on my mesh; and instead of exporting all the output into files, I would like to store the `obj` output internally, and use a slider control at which stage the simulation is, etc...

**Comment by liminchen** [comment]
Thanks for your interest in incorporating it into your project! Although it is possible, we admit that it is not designed for it so it would take efforts to make it happen given the current structure of the code. 
However, if you want to write your own optimization time integrator, then we provide straightforward API in the ipc-toolkit repository for convenience.
