### ISSUE TITLE
Can IPC be used to simulate voxel-based object

### ISSUE THREAD

**Issue by Ricahrd-Li** [ipc-sim/IPC#26]
Hi, Thanks for your great work!!

I'd like to know if IPC is able to be used to simulate contact between voxel-based objects with inner voxels, like:
![image](https://user-images.githubusercontent.com/47491676/141716234-b9056d4e-33a2-415b-bdcb-098352973639.png)

instead of the mesh-based representation which can only represent the surface of an object:
![image](https://user-images.githubusercontent.com/47491676/141716349-b5266dc7-1541-4d13-ae3b-9a5bfe62598d.png)

However, in the example, it seems all objects are represented as surface mesh without inner structures. 

Thanks!

**Comment by liminchen** [comment]
Hi, 

Thanks for your interest in our work!

Regard your questions, first, note that the simulator in this repo takes tetrahedral mesh as input, which is a volumetric mesh. IPC then extracts the surface for contact processing. If there is a hole inside, IPC will also extract the inner surface.

Similarly, if the voxel-based shape is tessellated as a tetrahedral mesh, IPC can automatically handle it. If it is represented as a VDB or something else, then the key is to figure out a way to define the distances between surface primitives.

**Comment by Ricahrd-Li** [comment]
Thanks for your reply!
