### ISSUE TITLE
Issue will running 2fallingcubes example.  

### ISSUE THREAD

**Issue by nburgessCarbon** [ipc-sim/IPC#3]
Hello, 
When running the 2cubesFall.txt example.  I get the following error : X11: The DISPLAY environment variable is missingThe GLFW library is not initializedThe GLFW library is not initializedThe GLFW library is not initializedSegmentation fault (core dumped).  I think the problem may be that I'm running on a remote machine using a non-x11 terminal.  Is there a way to disable the viz and have IPC dump files I can read in later?

**Comment by zfergus** [comment]
Yes, you can use the option`-DIPC_WITH_OPENGL=OFF` with `cmake` or set it interactively with `ccmake`. The output files will be dumped into an `output` directory located in the directory you run IPC from.

**Comment by binoyp** [comment]
Hi ,

I recompiled with `-DIPC_WITH_OPENGL=OFF`.  But i am getting following message instead of GLFW
`[2020-07-12 14:05:54.377] [critical] Not offiline mode supported only with opengl
Segmentation fault (core dumped)`

**Comment by zfergus** [comment]
Ah, I forgot to mention that in order to run without the viewer you have to change the first argument to the IPC_bin. If the first argument is `10` it runs with the viewer and if it is `100` it runs without.

If you are using `batch.py` then change line 30 to:
```python
runCommand += progPath + ' 100 ' + inputFolderPath + inputModelNameI + ' t' + numOfThreads
```

I will add a cmd-line option to that script to make it easier to choose.

**Comment by zfergus** [comment]
I also forgot to mention in my original reply that you only need to compile with `-DIPC_WITH_OPENGL=OFF` if your system does not have the necessary OpenGL libraries installed. If the compilation works with `-DIPC_WITH_OPENGL=ON`, then you can still run without the viewer using the above method.

**Comment by zfergus** [comment]
In my latest commit (a02cad196e408232d16a414640c5abcfbf630590), I added a `--offline` option to `batch.py` to run IPC in offline mode. I also updated the README with the information I wrote above.

**Comment by nburgessCarbon** [comment]
Thanks Zach, I'll be trying that tomorrow when I get to work.

**Comment by binoyp** [comment]
Thank you, It worked.

**Comment by nburgessCarbon** [comment]
Thanks Zach, everything works great now.
