### ISSUE TITLE
how to link SuitSparse to IPC-master on Windows

### ISSUE THREAD

**Issue by ShaYito** [ipc-sim/IPC#31]
I am using Windows and am new to SuitSparse. I wonder how to link SuitSparse to IPC-master.

I clone SuitSparse and build it as below. 

![图片](https://user-images.githubusercontent.com/52732323/147926602-e7848a26-44b7-4f3f-b8fe-72a2dba4426d.png)

When I build IPC-master, the output is as below

![图片](https://user-images.githubusercontent.com/52732323/147926349-02af6b95-5e5e-4eae-b0fc-6c6dbde0f393.png)

What else should I do to use SuitSparse in IPC?

**Comment by WeakBoss** [comment]
use linux System to build the project  :)

**Comment by CCxxCxCxCx** [comment]
Hello, I have the same problem, has this problem been solved? @ShaYito
