### ISSUE TITLE
element hessian matrix / stress differentials computation of Neo-Hookean material

### ISSUE THREAD

**Issue by Chenw831X** [ipc-sim/IPC#36]
Hi, when I read IPC's code about how to compute tetrahedron element hessian matrix of Neo-Hookean material, I found it difficult to figure out, mainly confused of this function `Energy<dim>::compute_dP_div_dF`.
I have read Sifakis's SIGGRAPH Course note (FEM simulation of 3D deformable solids: A practitioner's guide to theory, discretization and model reduction), but still can't correspond to the **formula of stress differentials** and **IPC's code**, having no idea about the meaning of `BLeftCoef`, `rightCoef`.

I want to know whether **a detailed formulas derivation of stress differentials in IPC's code** or **any related reference documents** could be provided. I really appreciate your help!

**Comment by liminchen** [comment]
Hello! You may want to check https://www.math.ucla.edu/~cffjiang/research/mpmcourse/mpmcourse.pdf section 6.4.2.

**Comment by Chenw831X** [comment]
Okay! Thank you very much for your timely reply!
