### ISSUE TITLE
Output interval control

### ISSUE THREAD

**Issue by nburgessCarbon** [ipc-sim/IPC#5]
I'm having trouble getting IPC to output and .obj file every timestep.  I looked over the documentation and there is an input called playBackSpeed.  I've tried setting this value to 1 and to a speed that that equals  number of time steps/simulation end time.  Neither of these setting has produced a 1.obj or a 2.obj file after Timestep 1 and 2 are completed.  

Any help would be appreciated.  

Thanks, 
Nick

**Comment by liminchen** [comment]
Hi Nick,

Forgive me that the playBackSpeed setting is too complicated, it has to be set to a value such that playing back in that speed at about 30 frame/s requires all objs from each time step, it will output every obj. So to ensure every time step has the output, simply setting it to a tiny value like 1e-20 should definitely work.

Minchen

**Comment by nburgessCarbon** [comment]
Thanks Minchen, that works perfectly.  Sorry to ask such a trivial question, but I got confused.  

Nick
