### ISSUE TITLE
CMake Build Fails to Download Eigen

### ISSUE THREAD

**Issue by breannansmith** [ipc-sim/IPC#9]
Following the build instructions on macOS, I obtain the following error:
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2' failed
         status_code: 22
         status_string: "HTTP response code said error"
Navigating the to the quoted URL, Bitbucket reports that:
          Repository unavailable
          Bitbucket no longer supports Mercurial repositories.

**Comment by zfergus** [comment]
Looks like Eigen had moved over to GitLab, and we need to update the CMake download.

**Comment by zfergus** [comment]
I updated the problematic dependencies. Could you please try with the latest commit?

**Comment by breannansmith** [comment]
The latest commit fixes the Eigen issue in my tests -- thanks for the super quick fix!
